################################################
# Server configurations
################################################
server:
  connector:
    # Changing port is available for embedded server only
    # Is is not possible to change port for deploying application on external server
    port: ${PORT:8080}


################################################
# Application (global) configurations
################################################
application:
  # License path
  # Absolute or relative path to GroupDocs license file
  licensePath: ${LIC_PATH:}
  # Host name or ip for server instance
  hostAddress: ${HOST_ADDRESS:}

################################################
# Common configurations
################################################
common:
  # File rewriting on document uploading
  # Set false to keep both files
  # Set true to replace files with same name
  rewrite: ${REWRITE:true}
  # Page navigation
  # Set false to disable document navigation (go to next, previous, last and first page)
  pageSelector: true
  # Document download
  # Set false to disable document download
  download: ${DOWNLOAD_ON:true}
  # Document upload
  # Set false to disable document upload
  upload: ${UPLOAD_ON:true}
  # File browser
  # Set false to disable document browse
  browse: ${BROWSE_ON:true}


################################################
# GroupDocs.Conversion configurations
################################################
conversion:
  # Files directory path
  # Absolute or relative path to files directory
  filesDirectory: ${FILES_DIR:DocumentSamples}
  # Result files directory path
  # Absolute path to result files directory
  resultDirectory: ${RESULT_DIR:DocumentSamples/Conversion/Converted}
